import { StyleSheet } from 'react-native';

import { palette } from '@/constants/todo-theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.canvas,
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
  },
  logoutButton: {
    position: 'absolute',
    top: 12,
    left: 18,
    zIndex: 2,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderWidth: 1,
    borderColor: palette.line,
    shadowColor: '#AD713B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 2,
  },
  logoutButtonTapTarget: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutIcon: {
    transform: [{ scaleX: -1 }],
  },
  loginShell: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 22,
    alignItems: 'center',
  },
  loginHero: {
    width: '100%',
    alignItems: 'center',
    overflow: 'hidden',
    paddingTop: 6,
    paddingBottom: 10,
  },
  loginMascotImage: {
    width: 236,
    height: 206,
    marginBottom: -2,
  },
  loginTitle: {
    color: palette.ink,
    fontSize: 28,
    fontFamily: 'Nunito-Black',
    lineHeight: 34,
    letterSpacing: 0,
    textAlign: 'center',
  },
  loginSubtitle: {
    color: palette.muted,
    fontSize: 16,
    fontFamily: 'Nunito-Bold',
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 14,
    maxWidth: 310,
    textAlign: 'center',
  },
  loginCard: {
    width: '100%',
    maxWidth: 360,
    gap: 12,
  },
  field: {
    gap: 8,
  },
  fieldLabel: {
    color: palette.ink,
    fontSize: 12,
    fontFamily: 'Nunito-Bold',
  },
  loginInputWrap: {
    minHeight: 62,
    borderRadius: 28,
    paddingHorizontal: 22,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.line,
    shadowColor: '#AC6C31',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  loginInput: {
    flex: 1,
    color: palette.ink,
    fontSize: 16,
    fontFamily: 'Nunito-SemiBold',
    paddingVertical: 0,
  },
  loginButton: {
    minHeight: 62,
    borderRadius: 28,
    marginTop: 4,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    backgroundColor: palette.butter,
    shadowColor: '#AC6C31',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  loginButtonDisabled: {
    opacity: 0.5,
  },
  loginButtonText: {
    color: palette.white,
    fontSize: 15,
    fontFamily: 'Nunito-ExtraBold',
  },
  mascotCollapsible: {
    overflow: 'hidden',
  },
  focusStateCollapsible: {
    overflow: 'hidden',
  },
  mascotCard: {
    height: 306,
    paddingHorizontal: 28,
    paddingTop: 6,
    paddingBottom: 10,
    alignItems: 'center',
  },
  mascotImage: {
    width: 236,
    height: 206,
    marginTop: 0,
    marginBottom: -2,
  },
  counterTitle: {
    color: palette.ink,
    fontSize: 28,
    fontFamily: 'Nunito-Black',
    letterSpacing: 0,
  },
  counterSubtitle: {
    color: palette.muted,
    fontSize: 16,
    fontFamily: 'Nunito-Bold',
    marginTop: 8,
  },
  focusStateCard: {
    height: 350,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  focusStateTitle: {
    color: palette.ink,
    fontSize: 26,
    fontFamily: 'Nunito-Black',
    textAlign: 'center',
  },
  focusStateSubtitle: {
    color: palette.muted,
    fontSize: 16,
    fontFamily: 'Nunito-Bold',
    marginTop: 10,
    maxWidth: 300,
    textAlign: 'center',
    lineHeight: 22,
  },
  taskScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 18,
  },
  composer: {
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 18,
  },
  inputWrap: {
    minHeight: 62,
    borderRadius: 28,
    paddingLeft: 22,
    paddingRight: 11,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.line,
    shadowColor: '#AC6C31',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  taskInput: {
    flex: 1,
    color: palette.ink,
    fontSize: 16,
    fontFamily: 'Nunito-SemiBold',
    paddingVertical: 0,
  },
  addTaskButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.butter,
  },
  addTaskButtonDisabled: {
    opacity: 0.45,
  },
  section: {
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    marginBottom: 10,
  },
  sectionTitle: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: 'Nunito-ExtraBold',
    textTransform: 'uppercase',
  },
  sectionCount: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: 'Nunito-Bold',
  },
  taskList: {
    gap: 12,
  },
  swipeHintText: {
    color: palette.muted,
    opacity: 0.72,
    fontSize: 11,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.2,
    textAlign: 'right',
    paddingHorizontal: 6,
    marginBottom: -2,
  },
  taskExitWrap: {
    overflow: 'hidden',
  },
  taskSwipeWrap: {
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  deleteReveal: {
    width: 64,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  deleteIconBubble: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.butter,
  },
  taskRow: {
    minHeight: 72,
    borderRadius: 28,
    paddingVertical: 13,
    paddingLeft: 22,
    paddingRight: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.line,
    shadowColor: '#AC6C31',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  taskRowCompleted: {
    backgroundColor: palette.white,
  },
  checkbox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: 'rgba(255,255,255,0.82)',
  },
  checkboxCompleted: {
    borderColor: palette.butter,
    backgroundColor: palette.butter,
  },
  checkmarkWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskContent: {
    flex: 1,
    gap: 3,
  },
  taskTitle: {
    color: palette.ink,
    fontSize: 16,
    fontFamily: 'Nunito-ExtraBold',
    lineHeight: 22,
  },
  taskTitleCompleted: {
    color: palette.ink,
    opacity: 0.72,
    textDecorationLine: 'line-through',
  },
  taskMeta: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: 'Nunito-Regular',
  },
  emptyState: {
    minHeight: 72,
    paddingHorizontal: 22,
    justifyContent: 'center',
  },
  emptyText: {
    color: palette.muted,
    fontSize: 16,
    fontFamily: 'Nunito-SemiBold',
    lineHeight: 22,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
  },
});
